version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  testing_poststeps:
    parameters:
      exit_code:
        type: integer
        default: 0
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Fail or Pass
          command: exit << parameters.exit_code >>

workflows:
  main:
    jobs:
      - testing_poststeps:
          exit_code: 1
          post-steps:
            - run:
                command: echo "try to use an Orb command"
            - docker/pull:
                image: "alpine"
